@startuml ContextoOperacion
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../textos/modulos.puml
!include ../textos/modelos.puml
!include ../textos/sistemas_externos_cumplo.puml

LAYOUT_WITH_LEGEND()

title Contexto de sistemas Módulo Ciclo de vida de la Operación

System(modulo_operaciones, $TITULO_CICLO_VIDA_OPERACION,$DESCRIPCION_CICLO_VIDA_OPERACION )

System_Ext(modulo_autenticacion, $TITULO_AUTENTICACION , $DESCRIPCION_AUTENTICACION)
System_Ext(modulo_registro_actores,$TITULO_REGISTRO_ACTORES ,$DESCRIPCION_REGISTRO_ACTORES )
System_Ext(modulo_cuentas_virtuales, $TITULO_CUENTAS_VIRTUALES ,$DESCRIPCION_CUENTAS_VIRTUALES )
System_Ext(modulo_respaldo_facturas, $TITULO_RESPALDOS, $DESCRIPCION_RESPALDOS )
System_Ext(modulo_autorizacion,$TITULO_AUTORIZACION , $DESCRIPCION_AUTORIZACION)



'Relaciones sistema/módulos

Rel(modulo_registro_actores, modulo_operaciones, $MODELO_ACTOR)
Rel(modulo_cuentas_virtuales, modulo_operaciones,$MODELO_CUENTA_VIRTUAL )
Rel(modulo_operaciones, modulo_cuentas_virtuales, $MODELO_PAGO )
Rel( modulo_autenticacion,modulo_operaciones, $MODELO_ACCESO )
Rel( modulo_respaldo_facturas, modulo_operaciones,$MODELO_RESPALDO )
Rel(modulo_autorizacion, modulo_operaciones,$MODELO_AUTORIZACION )

'Relaciones módulos/sistemas externos


@enduml
