@startuml ContextoPanoramicoRespaldosFacturas
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

!include ../textos/modulos.puml
!include ../textos/modelos.puml
!include ../textos/sitios.puml
!include ../textos/sistemas_externos_cumplo.puml
!include ../textos/usuarios.puml
!include ../textos/perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Diagrama Panorámico de sistema Módulo Respaldos y Facturas

Enterprise_Boundary(c0, $PERIMETRO_CUMPLO) {
    System_Boundary(sistemas_modulos, $PERIMETRO_MODULOS){
        System(modulo_respaldo_facturas, $TITULO_RESPALDOS, $DESCRIPCION_RESPALDOS )
        System_Ext(modulo_operaciones, $TITULO_CICLO_VIDA_OPERACION,$DESCRIPCION_CICLO_VIDA_OPERACION )
        System_Ext(modulo_autenticacion, $TITULO_AUTENTICACION , $DESCRIPCION_AUTENTICACION)
        System_Ext(modulo_registro_actores,$TITULO_REGISTRO_ACTORES ,$DESCRIPCION_REGISTRO_ACTORES )
        System_Ext(modulo_autorizacion,$TITULO_AUTORIZACION , $DESCRIPCION_AUTORIZACION)
    }
}

System_Boundary(sistemas_externos, $PERIMETRO_SISTEMAS_EXTERNOS){
    System_Ext(hubspot, $S_EXT_TITULO_HUBSPOT,$S_EXT_DESCRIPCION_HUBSPOT )
    System_Ext(cavali, $S_EXT_TITULO_CAVALI,$S_EXT_DESCRIPCION_CAVALI )
    System_Ext(clay, $S_EXT_TITULO_CLAY,$S_EXT_DESCRIPCION_CLAY )
    System_Ext(abstrahere, $S_EXT_TITULO_ABSTRAHERE,$S_EXT_DESCRIPCION_ABSTRAHERE )
    System_Ext(satws, $S_EXT_TITULO_SATWS,$S_EXT_DESCRIPCION_SATWS )
    System_Ext(radian, $S_EXT_TITULO_RADIAN,$S_EXT_DESCRIPCION_RADIAN )
    System_Ext(intiza, $S_EXT_TITULO_INTIZA,$S_EXT_DESCRIPCION_INTIZA )
    System_Ext(fapro, $S_EXT_TITULO_FAPRO,$S_EXT_DESCRIPCION_FAPRO )
    System_Ext(sat, $S_EXT_TITULO_SAT,$S_EXT_DESCRIPCION_SAT )
    System_Ext(sii, $S_EXT_TITULO_SII,$S_EXT_DESCRIPCION_SII )
    System_Ext(sunat, $S_EXT_TITULO_SUNAT,$S_EXT_DESCRIPCION_SUNAT )
    System_Ext(dian, $S_EXT_TITULO_DIAN,$S_EXT_DESCRIPCION_DIAN )
}


'RELACIONES DE SISTEMA
Rel_D(modulo_autorizacion, modulo_respaldo_facturas, $MODELO_AUTORIZACION)
Rel_U( modulo_autenticacion,modulo_respaldo_facturas, $MODELO_ACCESO )
Rel_D(modulo_registro_actores, modulo_respaldo_facturas, $MODELO_ACTOR)
Rel_R(modulo_respaldo_facturas, modulo_operaciones, $MODELO_RESPALDO)



'Relaciones módulos/sistemas externos
Rel_U( modulo_respaldo_facturas,hubspot, $MODELO_RESPALDO )
Rel_Back( modulo_respaldo_facturas,cavali, $MODELO_RESPALDO )
Rel( clay,modulo_respaldo_facturas, $MODELO_RESPALDO )
Rel( modulo_respaldo_facturas,abstrahere, $MODELO_RESPALDO )
Rel(satws, modulo_respaldo_facturas, $MODELO_RESPALDO )
Rel_Back( modulo_respaldo_facturas,radian, $MODELO_RESPALDO )
Rel(fapro, modulo_respaldo_facturas, $MODELO_RESPALDO )
Rel( modulo_respaldo_facturas,intiza, $MODELO_RESPALDO )


'Relaciones sistemas externos/sistemas externos

Rel_D( fapro, sii, "Se comunica con" )
Rel_L( clay,sii, "Se comunica con"  )
Rel_L( abstrahere,sii, "Se comunica con"  )
Rel_L( satws,sat, "Se comunica con"  )
Rel_L( cavali, sunat, "Se comunica con"  )
Rel_L( radian, dian, "Se comunica con"  )



'declaraciones para distribución espacial

'declaraciones para distribución espacial

Lay_D(fapro, clay)
'Lay_D(clay, abstrahere)
Lay_D(abstrahere, satws)
Lay_D(satws, cavali)
Lay_D(cavali, radian)


Lay_D(sii, sat)
Lay_D(sat, sunat)
Lay_D(sunat, dian)

Lay_R(fapro, sii)
Lay_R(clay, sii)
Lay_R(abstrahere, sii)
Lay_R(satws, sat)
Lay_R(cavali, sunat)
Lay_R(radian, dian)
Lay_D(clay, fapro)

Lay_U(fapro, hubspot)

Lay_U(fapro, intiza)
Lay_U(abstrahere, clay)
'Lay_U(hubspot, intiza)


Lay_D(clay,satws)



@enduml
