@startuml ContextoPanoramicoRespaldosFacturas
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

!include ../textos/modulos.puml
!include ../textos/modelos.puml
!include ../textos/sitios.puml
!include ../textos/sistemas_externos_cumplo.puml
!include ../textos/usuarios.puml
!include ../textos/perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Diagrama Panorámico de sistema Módulo Respaldos y Facturas
Person_Ext(solicitante,$TITULO_SOLICITANTE, $DESCRIPCION_SOLICITANTE )
Person_Ext(inversionista, $TITULO_INVERSIONISTA ,$DESCRIPCION_INVERSIONISTA )
Person_Ext(pagador,$TITULO_PAGADOR ,$DESCRIPCION_PAGADOR )
Person_Ext(agente_cumplo, $TITULO_AGENTE_CUMPLO,$DESCRIPCION_AGENTE_CUMPLO)



Enterprise_Boundary(c0, $PERIMETRO_CUMPLO) {
    System_Boundary(sistemas_modulos, $PERIMETRO_MODULOS){
        System(modulo_respaldo_facturas, $TITULO_RESPALDOS, $DESCRIPCION_RESPALDOS )
        'System(modulo_operaciones, $TITULO_CICLO_VIDA_OPERACION,$DESCRIPCION_CICLO_VIDA_OPERACION )
        System(modulo_autenticacion, $TITULO_AUTENTICACION , $DESCRIPCION_AUTENTICACION)
        System(modulo_autorizacion,$TITULO_AUTORIZACION , $DESCRIPCION_AUTORIZACION)

        'System_Ext(modulo_registro_actores,$TITULO_REGISTRO_ACTORES ,$DESCRIPCION_REGISTRO_ACTORES )
        'System_Ext(modulo_autorizacion,$TITULO_AUTORIZACION , $DESCRIPCION_AUTORIZACION)
    }

    System_Boundary(sistemas_sitios, $PERIMETRO_SITIOS){
        System_Ext(s_financiamiento,$TITULO_SITIO_FINANCIAMIENTO , $DESCRIPCION_SITIO_FINANCIAMIENTO )
        System_Ext(s_inversionista,$TITULO_SITIO_INVERSIONISTA ,$DESCRIPCION_SITIO_INVERSIONISTA )
        System_Ext(s_cuentas_x_pagar,$TITULO_SITIO_CXP ,$DESCRIPCION_SITIO_CXP )
        System_Ext(s_administracion, $TITULO_SITIO_ADMINISTRACION,$DESCRIPCION_SITIO_ADMINISTRACION )
        System_Ext(s_tesoreria, $TITULO_SITIO_TESORERIA,$DESCRIPCION_SITIO_TESORERIA )
    }
}



System_Boundary(sistemas_externos, $PERIMETRO_SISTEMAS_EXTERNOS){
    System_Ext(cavali, $S_EXT_TITULO_CAVALI,$S_EXT_DESCRIPCION_CAVALI )
    System_Ext(clay, $S_EXT_TITULO_CLAY,$S_EXT_DESCRIPCION_CLAY )
    System_Ext(abstrahere, $S_EXT_TITULO_ABSTRAHERE,$S_EXT_DESCRIPCION_ABSTRAHERE )
    System_Ext(satws, $S_EXT_TITULO_SATWS,$S_EXT_DESCRIPCION_SATWS )
    System_Ext(radian, $S_EXT_TITULO_RADIAN,$S_EXT_DESCRIPCION_RADIAN )
    System_Ext(intiza, $S_EXT_TITULO_INTIZA,$S_EXT_DESCRIPCION_INTIZA )
    System_Ext(fapro, $S_EXT_TITULO_FAPRO,$S_EXT_DESCRIPCION_FAPRO )
    System_Ext(sat, $S_EXT_TITULO_SAT,$S_EXT_DESCRIPCION_SAT )
    System_Ext(sii, $S_EXT_TITULO_SII,$S_EXT_DESCRIPCION_SII )
    System_Ext(sunat, $S_EXT_TITULO_SUNAT,$S_EXT_DESCRIPCION_SUNAT )
    System_Ext(dian, $S_EXT_TITULO_DIAN,$S_EXT_DESCRIPCION_DIAN )
}

System_Boundary(sistemas_externos_2, $PERIMETRO_SISTEMAS_EXTERNOS){
 System_Ext(hubspot, $S_EXT_TITULO_HUBSPOT,$S_EXT_DESCRIPCION_HUBSPOT )
 System_Ext(sist_externo_logs, "AWS Cloudwatch","Amazon web services" )
 System_Ext(sist_externo_notificacion, "AWS SNS","Amazon web services" )
 System_Ext(sist_externo_errores, "Sentry","Servicio de gestión de Errores de sistemas" )
 }


'RELACIONES DE SISTEMA
'Relaciones sistema/módulos
Rel_R(modulo_respaldo_facturas,modulo_autorizacion, "valida $MODELO_AUTORIZACION")
Rel_L( modulo_respaldo_facturas,modulo_autenticacion, "autentica $MODELO_ACCESO", HTTPS )

'Relaciones usuarios/sitios

Rel(agente_cumplo, s_tesoreria, $DOMINIO_SITIO_TESORERIA)
Rel(solicitante, s_financiamiento,$DOMINIO_SITIO_FINANCIAMIENTO)
Rel(inversionista, s_inversionista,$DOMINIO_SITIO_INVERSIONISTA)
Rel(pagador, s_cuentas_x_pagar, $DOMINIO_SITIO_CXP)
Rel(agente_cumplo, s_administracion,$DOMINIO_SITIO_ADMINISTRACION)



'Relaciones sitios/módulos

Rel(s_tesoreria,modulo_respaldo_facturas, "obtiene $MODELO_RESPALDO" )
Rel(s_administracion,modulo_respaldo_facturas, "obtiene $MODELO_RESPALDO" )
Rel(s_cuentas_x_pagar,modulo_respaldo_facturas, "obtiene y registra $MODELO_RESPALDO" )
Rel(s_financiamiento,modulo_respaldo_facturas,"obtiene $MODELO_RESPALDO"  )
Rel(s_inversionista,modulo_respaldo_facturas, "obtiene $MODELO_RESPALDO" )


'Relaciones módulos/sistemas externos
Rel( modulo_respaldo_facturas,intiza, "gestiona cobranza de $MODELO_RESPALDO",$tags="pendiente" )
Rel( sist_externo_notificacion,hubspot, "notifica $MODELO_RESPALDO",$tags="pendiente" )
Rel( modulo_respaldo_facturas,cavali, "cede $MODELO_RESPALDO" )
Rel( modulo_respaldo_facturas,abstrahere, "cede $MODELO_RESPALDO"  )
Rel( modulo_respaldo_facturas,radian, "extrae $MODELO_RESPALDO",$tags="pendiente")
Rel( modulo_respaldo_facturas,satws, "extrae $MODELO_RESPALDO" )
Rel( modulo_respaldo_facturas,clay, "extrae $MODELO_RESPALDO" )
Rel( modulo_respaldo_facturas,fapro, "extrae $MODELO_RESPALDO" ,$tags="pendiente")

Rel( modulo_respaldo_facturas,sist_externo_errores, "gestiona errores de sistema" ,$tags="pendiente")
Rel( modulo_respaldo_facturas,sist_externo_notificacion, "notifica cambios en facturas" ,$tags="pendiente")
Rel( modulo_respaldo_facturas,sist_externo_logs, "registra logs de operaciones del sistemas" ,$tags="pendiente")

Lay_R(radian,cavali )
Lay_L(clay,fapro )



'Relaciones sistemas externos/sistemas externos

Rel( fapro, sii, "Se comunica con" )
Rel( clay,sii, "Se comunica con"  )
Rel( abstrahere,sii, "Se comunica con"  )
Rel( satws,sat, "Se comunica con"  )
Rel( cavali, sunat, "Se comunica con"  )
Rel( radian, dian, "Se comunica con"  )



'declaraciones para distribución espacial
Lay_D(sistemas_sitios, sistemas_modulos)
Lay_D(sistemas_modulos,sistemas_externos )





@enduml
