@startuml ContextoCuentasReales
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../C4_Context.puml
!include ../textos/modulos.puml
!include ../textos/modelos.puml
!include ./sistemas_externos_cuentas_reales.puml

LAYOUT_WITH_LEGEND()

title Contexto de sistemas Módulo Cuentas Reales

Enterprise_Boundary(c0, $PERIMETRO_CUMPLO ) {
  
    System_Boundary(sistemas_modulos, $PERIMETRO_MODULOS){
        System(modulo_cuentas_reales, $TITULO_CUENTAS_REALES, $DESCRIPCION_CUENTAS_REALES)
        System_Ext(modulo_autenticacion, $TITULO_AUTENTICACION , $DESCRIPCION_AUTENTICACION)
        System_Ext(modulo_autorizacion,$TITULO_AUTORIZACION , $DESCRIPCION_AUTORIZACION)
        System_Ext(modulo_registro_actores,$TITULO_REGISTRO_ACTORES ,$DESCRIPCION_REGISTRO_ACTORES )
        System_Ext(modulo_cuentas_virtuales, $TITULO_CUENTAS_VIRTUALES ,$DESCRIPCION_CUENTAS_VIRTUALES )
    }
}
System_Boundary(sistemas_externos, $PERIMETRO_SISTEMAS_EXTERNOS){
    System_Ext(fintoc, $S_EXT_TITULO_FINTOC, $S_EXT_DESCRIPCION_FINTOC)
    System_Ext(prometeo,$S_EXT_TITULO_PROMETEO , $S_EXT_DESCRIPCION_PROMETEO)
    System_Ext(khipu,$S_EXT_TITULO_KHIPU , $S_EXT_DESCRIPCION_KHIPU)
    System_Ext(stp,$S_EXT_TITULO_STP , $S_EXT_DESCRIPCION_STP)
    'BANCOS CL
    System_Ext(banco_santander_cl,$S_EXT_TITULO_BANCO_SANTANDER_CL , $S_EXT_DESCRIPCION_BANCO_SANTANDER_CL)
    System_Ext(banco_bci_cl,$S_EXT_TITULO_BANCO_BCI_CL , $S_EXT_DESCRIPCION_BANCO_BCI_CL)
    System_Ext(banco_bice_cl,$S_EXT_TITULO_BANCO_BICE_CL , $S_EXT_DESCRIPCION_BANCO_BICE_CL)
    System_Ext(banco_estado_cl,$S_EXT_TITULO_BANCO_ESTADO_CL , $S_EXT_DESCRIPCION_BANCO_ESTADO_CL)
    'BANCOS MX
    System_Ext(banco_bbva_mx,$S_EXT_TITULO_BANCO_BBVA_MX , $S_EXT_DESCRIPCION_BANCO_BBVA_MX)
    System_Ext(banco_scotiabank_mx,$S_EXT_TITULO_BANCO_SCOTIABANK_MX , $S_EXT_DESCRIPCION_BANCO_SCOTIABANK_MX)
    System_Ext(banco_inbursa_mx,$S_EXT_TITULO_BANCO_INBURSA_MX , $S_EXT_DESCRIPCION_BANCO_INBURSA_MX)
    System_Ext(banco_bxmas_mx,$S_EXT_TITULO_BANCO_BXMAS_MX , $S_EXT_DESCRIPCION_BANCO_BXMAS_MX)
    System_Ext(banco_jeeves_mx,"$S_EXT_TITULO_BANCO_JEEVES_MX**" , $S_EXT_DESCRIPCION_BANCO_JEEVES_MX)

    'BANCOS PE
    System_Ext(banco_bcp_pe,$S_EXT_TITULO_BANCO_BCP_PE , $S_EXT_DESCRIPCION_BANCO_BCP_PE)

}

'RELACIONES DE SISTEMA


'Relaciones usuarios/sitios

'Relaciones sitios/módulos



'Relaciones sistema/módulos
Rel_R(modulo_cuentas_reales,modulo_registro_actores, obtiene cuentas virtuales de $MODELO_ACTOR)
Rel_L(modulo_cuentas_reales,modulo_autenticacion, autentica $MODELO_ACCESO)
Rel_U(modulo_cuentas_reales,modulo_cuentas_virtuales, "registra movimientos virtuales para $MODELO_DEPOSITO y $MODELO_NOMINA")


'Relaciones módulos/sistemas externos
Rel_D( modulo_cuentas_reales,fintoc, obtiene $MODELO_TRANSACCION)
Rel_D(  modulo_cuentas_reales,prometeo, obtiene $MODELO_TRANSACCION)
Rel_D(  modulo_cuentas_reales,khipu, obtiene $MODELO_TRANSACCION e identificador de Pago)
Rel_D(  khipu, banco_bci_cl, obtiene $MODELO_TRANSACCION e identificador de Pago)
Rel_D(  modulo_cuentas_reales,stp, obtiene $MODELO_TRANSACCION)

'Relaciones sistemas externos/sistemas externos
Rel(fintoc, banco_santander_cl, obtiene movimientos bancarios)
Rel(fintoc, banco_bci_cl, obtiene movimientos bancarios)
Rel(fintoc, banco_bice_cl, obtiene movimientos bancarios)

Rel(prometeo, banco_bcp_pe, obtiene movimientos bancarios)



'declaraciones para distribución espacial
Lay_D(sistemas_modulos, sistemas_externos )

@enduml
