@startuml ContextoPanoramicoCuentasReales
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../C4_Context.puml
!include ../textos/modulos.puml
!include ../textos/usuarios.puml


'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Diagrama Panorámico de sistema Módulo Cuentas Reales

Person_Ext(agente_cumplo, $TITULO_AGENTE_CUMPLO, $DESCRIPCION_AGENTE_CUMPLO)
Enterprise_Boundary(c0, "Cumplo" ) {
    System_Ext(s_tesoreria, "Sitio Tesorería", " permite operar como Agente Cumplo de forma segura con procesos sensibles en Cumplo.")
    System( modulo_cuentas_reales, $TITULO_CUENTAS_REALES, $DESCRIPCION_CUENTAS_REALES)
    System_Ext(modulo_autenticacion, $TITULO_AUTENTICACION , $DESCRIPCION_AUTENTICACION)
    System_Ext(modulo_registro_actores, "Módulo Registro actores", "El contenedor de Actores (Empresa/Persona) y su perfil detallado.")
    System_Ext(modulo_cuentas_virtuales, "Módulo Cuentas Virtuales", "Gestión de cuentas virtuales, movimientos y saldos.")
    System_Ext(modulo_operaciones, "Ciclo de vida Operación", "Gestión de la operación y los procesos que giran en torno a la misma.")
    System_Ext(modulo_api_cumplo, "Api Cumplo", "Expone servicios para el consumo de sistemas externos a Cumplo y sitios.")

}
System_Boundary(sistemas_externos, "Sistemas externos"){
    System_Ext(fintoc, "Fintoc", "API simple para hacer conciliación bancaria.")
    System_Ext(prometeo, "Prometeo", "API simple para hacer conciliación bancaria.")

}



'RELACIONES DE SISTEMA
'Relaciones sistema/módulos
Rel(modulo_registro_actores, modulo_cuentas_reales, "Actor")
Rel(modulo_cuentas_virtuales, modulo_cuentas_reales, "Movimiento")
Rel_U(modulo_operaciones, modulo_cuentas_reales, "Pago")
Rel_U(modulo_autenticacion, modulo_cuentas_reales, "Acceso")


'Relaciones usuarios/sitios
 
 Rel(agente_cumplo, s_tesoreria, "https://treasury.cumplo.com",)


'Relaciones sitios/módulos

Rel(s_tesoreria,modulo_cuentas_reales, "asocia depositos y gestiona nóminas usando", "HTTPS")


'Relaciones módulos/sistemas externos
Rel_R( fintoc, modulo_cuentas_reales, "Transacción bancaria")
Rel_R( prometeo, modulo_cuentas_reales, "Transacción bancaria")


@enduml
