@startuml ContextoPanoramicoCuentasBancosCumplo
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../C4_Context.puml
!include ../textos/modulos.puml
!include ../textos/modelos.puml
!include ../textos/sitios.puml
!include ./sistemas_externos_cuentas_reales.puml
!include ../textos/usuarios.puml
!include ../textos/perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Diagrama Panorámico Bancos Cumplo

Person_Ext(agente_cumplo, $TITULO_AGENTE_CUMPLO, $DESCRIPCION_AGENTE_CUMPLO)
Person_Ext(solicitante,$TITULO_SOLICITANTE, $DESCRIPCION_SOLICITANTE )
Person_Ext(inversionista, $TITULO_INVERSIONISTA ,$DESCRIPCION_INVERSIONISTA )
Person_Ext(pagador,$TITULO_PAGADOR ,$DESCRIPCION_PAGADOR )
Person_Ext(accionista,"Accionista" , "Aporte de capital" )

Person_Ext(proveedor_externo,"Proveedor Externo" , "Provee servicios o insumos a cumplo" )

System_Boundary(sistemas_externos, $PERIMETRO_SISTEMAS_EXTERNOS){
  'BANCOS
    System_Boundary(cl,"CL"){
        System_Boundary(cuentas_santander_pedro,"Santander"){

            System_Ext(banco_santander_cl_cuenta_1_p,"6586896-2", "Operaciones")
            System_Ext(banco_santander_cl_cuenta_2_p,"8413460-0", "Operaciones")
            System_Ext(banco_santander_cl_cuenta_3_p,"6848412-0" , "administracion")
            System_Ext(banco_santander_cl_cuenta_4_p,"7013168-4" , "administracion")
            System_Ext(banco_santander_cl_cuenta_5_p,"051-0037411-2" , "administracion")
            System_Ext(banco_santander_cl_cuenta_6_p,"77134556" , "Operaciones")
            System_Ext(banco_santander_cl_cuenta_7_p,"0-000-6887476-9" , "administracion")
         

        }
        System_Boundary(cuentas_banco_estado_cl,"Banco Estado"){
            System_Ext(banco_estado_cl_cuenta_1,"8072388" , "Adminsitracion")

        }
        System_Boundary(cuentas_banco_bice_cl,"Banco Bice"){
            System_Ext(banco_bice_cl_cuenta_1,"8072388" , "Administracion")

        }
        System_Boundary(cuentas_banco_bci_cl,"Banco BCI"){
            System_Ext(banco_bci_cl_cuenta_1,"61247286" , "Operaciones")

        }
    }
    System_Boundary(mx,"MX"){
        System_Ext(banco_bbva_mx,$S_EXT_TITULO_BANCO_BBVA_MX , $S_EXT_DESCRIPCION_BANCO_BBVA_MX)
        System_Ext(banco_scotiabank_mx,$S_EXT_TITULO_BANCO_SCOTIABANK_MX , $S_EXT_DESCRIPCION_BANCO_SCOTIABANK_MX)
        System_Ext(banco_inbursa_mx,$S_EXT_TITULO_BANCO_INBURSA_MX , $S_EXT_DESCRIPCION_BANCO_INBURSA_MX)
        System_Ext(banco_bxmas_mx,$S_EXT_TITULO_BANCO_BXMAS_MX , $S_EXT_DESCRIPCION_BANCO_BXMAS_MX)
        System_Ext(banco_jeeves_mx,"$S_EXT_TITULO_BANCO_JEEVES_MX**" , $S_EXT_DESCRIPCION_BANCO_JEEVES_MX)

    }
    System_Boundary(pe,"PE"){
        System_Ext(banco_bcp_pe,$S_EXT_TITULO_BANCO_BCP_PE , $S_EXT_DESCRIPCION_BANCO_BCP_PE)
    }
    System_Boundary(us,"US"){
        System_Ext(banco_brex_us,$S_EXT_TITULO_BANCO_BREX_US , $S_EXT_DESCRIPCION_BANCO_BREX_US)
    }
}

'RELACIONES DE SISTEMA
Rel(agente_cumplo, banco_santander_cl_cuenta_1_p, "transfiere dinero via nóminas desde")
Rel( banco_santander_cl_cuenta_1_p, inversionista, "gira dinero a cuenta bancaria de")
Rel( banco_santander_cl_cuenta_1_p, solicitante, "gira dinero a cuenta bancaria de")
Rel( pagador, banco_santander_cl_cuenta_1_p, "transfiere pagos")


Rel(banco_santander_cl_cuenta_1_p, banco_santander_cl_cuenta_2_p, "almacena saldos de cuentas T en")
Rel( banco_santander_cl_cuenta_2_p, solicitante, "gira dinero a cuenta bancaria de")


Rel( accionista,banco_santander_cl_cuenta_4_p, aporte de capital)

Rel(banco_santander_cl_cuenta_5_p,proveedor_externo, "pago proveedores")

Rel(agente_cumplo, banco_santander_cl_cuenta_6_p, "transfiere dinero via nóminas desde")
Rel( banco_santander_cl_cuenta_6_p, inversionista, "gira dinero a cuenta bancaria de")
Rel( banco_santander_cl_cuenta_6_p, solicitante, "gira dinero a cuenta bancaria de")
Rel( pagador, banco_santander_cl_cuenta_6_p, "transfiere pagos")


@enduml
