@startuml ContextoPanoramicoCuentasReales
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../C4_Context.puml
!include ../textos/modulos.puml
!include ../textos/modelos.puml
!include ../textos/sitios.puml
!include ./sistemas_externos_cuentas_reales.puml
!include ../textos/usuarios.puml
!include ../textos/perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Diagrama Panorámico Módulo Cuentas Reales

Person_Ext(agente_cumplo, $TITULO_AGENTE_CUMPLO, $DESCRIPCION_AGENTE_CUMPLO)
'Person_Ext(solicitante,$TITULO_SOLICITANTE, $DESCRIPCION_SOLICITANTE )
'Person_Ext(inversionista, $TITULO_INVERSIONISTA ,$DESCRIPCION_INVERSIONISTA )
'Person_Ext(pagador,$TITULO_PAGADOR ,$DESCRIPCION_PAGADOR )

Enterprise_Boundary(c0, $PERIMETRO_CUMPLO ) {
    System_Boundary(sistemas_sitios, $PERIMETRO_SITIOS){
        System_Ext(s_tesoreria, $TITULO_SITIO_TESORERIA,$DESCRIPCION_SITIO_TESORERIA )
    }
    System_Boundary(sistemas_modulos, $PERIMETRO_MODULOS){
        System(modulo_cuentas_reales, $TITULO_CUENTAS_REALES, $DESCRIPCION_CUENTAS_REALES)
        System_Ext(modulo_autenticacion, $TITULO_AUTENTICACION , $DESCRIPCION_AUTENTICACION)
        System_Ext(modulo_autorizacion,$TITULO_AUTORIZACION , $DESCRIPCION_AUTORIZACION)
        System_Ext(modulo_registro_actores,$TITULO_REGISTRO_ACTORES ,$DESCRIPCION_REGISTRO_ACTORES )
        System_Ext(modulo_cuentas_virtuales, $TITULO_CUENTAS_VIRTUALES ,$DESCRIPCION_CUENTAS_VIRTUALES )
    }
}
System_Boundary(sistemas_externos, $PERIMETRO_SISTEMAS_EXTERNOS){
    System_Ext(fintoc, $S_EXT_TITULO_FINTOC, $S_EXT_DESCRIPCION_FINTOC)
    System_Ext(prometeo,$S_EXT_TITULO_PROMETEO , $S_EXT_DESCRIPCION_PROMETEO)
    System_Ext(khipu,$S_EXT_TITULO_KHIPU , $S_EXT_DESCRIPCION_KHIPU)
    System_Ext(stp,$S_EXT_TITULO_STP , $S_EXT_DESCRIPCION_STP)
    'BANCOS
    System_Ext(banco_santander,$S_EXT_TITULO_BANCO_SANTANDER , $S_EXT_DESCRIPCION_BANCO_SANTANDER)
    System_Ext(banco_bci,$S_EXT_TITULO_BANCO_BCI , $S_EXT_DESCRIPCION_BANCO_BCI)
    System_Ext(banco_bice,$S_EXT_TITULO_BANCO_BICE , $S_EXT_DESCRIPCION_BANCO_BICE)
    System_Ext(banco_bbva,$S_EXT_TITULO_BANCO_BBVA , $S_EXT_DESCRIPCION_BANCO_BBVA)
    System_Ext(banco_jeeves,$S_EXT_TITULO_BANCO_JEEVES , $S_EXT_DESCRIPCION_BANCO_JEEVES)
    System_Ext(banco_scotiabank,$S_EXT_TITULO_BANCO_SCOTIABANK , $S_EXT_DESCRIPCION_BANCO_SCOTIABANK)
    System_Ext(banco_brex,$S_EXT_TITULO_BANCO_BREX , $S_EXT_DESCRIPCION_BANCO_BREX)
}

'RELACIONES DE SISTEMA


'Relaciones usuarios/sitios
 
 Rel_D(agente_cumplo, s_tesoreria, $DOMINIO_SITIO_TESORERIA)


'Relaciones sitios/módulos
Rel_D(s_tesoreria,modulo_cuentas_reales, "asocia depósitos y gestiona nóminas usando", "HTTPS")



'Relaciones sistema/módulos
Rel_R(modulo_cuentas_reales,modulo_registro_actores, obtiene cuentas virtuales de $MODELO_ACTOR)
Rel_L(modulo_cuentas_reales,modulo_autenticacion, autentica $MODELO_ACCESO)
Rel(modulo_cuentas_reales,modulo_cuentas_virtuales, "registra movimientos virtuales para $MODELO_DEPOSITO y $MODELO_NOMINA")


'Relaciones módulos/sistemas externos
Rel_U(fintoc, modulo_cuentas_reales, $MODELO_TRANSACCION)
Rel( prometeo, modulo_cuentas_reales, $MODELO_TRANSACCION)
'Relaciones sistemas externos/sistemas externos
Rel(fintoc, banco_santander, obtiene movimientos bancarios)
Rel(fintoc, banco_bci, obtiene movimientos bancarios)
Rel(fintoc, banco_bice, obtiene movimientos bancarios)



'declaraciones para distribución espacial
Lay_D(sistemas_sitios, sistemas_modulos)
Lay_D(sistemas_modulos,sistemas_externos )

@enduml
