@startuml BancosCumploSA
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../../C4_Context.puml
!include ../../textos/modulos.puml
!include ../../textos/modelos.puml
!include ../../textos/sitios.puml
!include ./../sistemas_externos_cuentas_reales.puml
!include ../../textos/usuarios.puml
!include ../../textos/perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Bancos Cumplo SA

Person_Ext(agente_cumplo, $TITULO_AGENTE_CUMPLO, $DESCRIPCION_AGENTE_CUMPLO)
Person_Ext(solicitante,$TITULO_SOLICITANTE, $DESCRIPCION_SOLICITANTE )
Person_Ext(inversionista, $TITULO_INVERSIONISTA ,$DESCRIPCION_INVERSIONISTA )
Person_Ext(pagador,$TITULO_PAGADOR ,$DESCRIPCION_PAGADOR )
Person_Ext(accionista,"Accionista" , "Aporte de capital" )

Person_Ext(proveedor_externo,"Proveedor Externo" , "Provee servicios o insumos a cumplo" )

System_Boundary(sistemas_externos, $PERIMETRO_SISTEMAS_EXTERNOS){
  
   System_Ext(khipu,$S_EXT_TITULO_KHIPU , $S_EXT_DESCRIPCION_KHIPU)

  'BANCOS
    Boundary(cl,"Cumplo SA"){
        Boundary(cuentas_santander_pedro,"Santander"){

            System_Ext(banco_santander_cl_cuenta_1_p,"6586896-2", "Operaciones, Cumplo Chile")
            System_Ext(banco_santander_cl_cuenta_2_p,"8413460-0", "Operaciones, Cumplo Chile")
            System_Ext(banco_santander_cl_cuenta_3_p,"6848412-0" , "administracion, Cumplo Chile")
            System_Ext(banco_santander_cl_cuenta_4_p,"7013168-4" , "administracion, Cumplo Chile")
            System_Ext(banco_santander_cl_cuenta_5_p,"051-0037411-2" , "administracion, Cumplo Chile")
         
        }
        Boundary(cuentas_banco_estado_cl,"Banco Estado"){
            System_Ext(banco_estado_cl_cuenta_1,"8072388" , "Adminsitracion")

        }
        Boundary(cuentas_banco_bice_cl,"Banco Bice"){
            System_Ext(banco_bice_cl_cuenta_1,"8072388" , "Administracion")

        }
        Boundary(cuentas_banco_bci_cl,"Banco BCI"){
            System_Ext(banco_bci_cl_cuenta_1,"61247286" , "Operaciones")

        }
    }
    
}

'RELACIONES DE SISTEMA
Rel_D(agente_cumplo, banco_santander_cl_cuenta_1_p, "transfiere dinero via nóminas desde")
Rel( banco_santander_cl_cuenta_1_p, inversionista, "gira dinero a cuenta bancaria de")
Rel( banco_santander_cl_cuenta_1_p, solicitante, "gira dinero a cuenta bancaria de")
Rel_R( pagador, banco_santander_cl_cuenta_1_p, "transfiere pagos")
Lay_D(agente_cumplo, sistemas_externos)
Lay_R(pagador, sistemas_externos)

Rel(banco_santander_cl_cuenta_1_p, banco_santander_cl_cuenta_2_p, "almacena saldos de cuentas T en")
Rel( banco_santander_cl_cuenta_2_p, solicitante, "gira dinero a cuenta bancaria de")


Rel( accionista,banco_santander_cl_cuenta_4_p, aporte de capital)

Rel_D(banco_santander_cl_cuenta_5_p,proveedor_externo, "pago proveedores")

Rel(inversionista, khipu,"transferencia")
Rel(khipu, banco_bci_cl_cuenta_1,"transferencia")

Rel(banco_bci_cl_cuenta_1,banco_santander_cl_cuenta_1_p,"gira dinero de inversiones" )

Rel(banco_santander_cl_cuenta_1_p,banco_santander_cl_cuenta_3_p, "gira ingresos de operación a" )


@enduml
