'Componentes RESPALDOS Y FACTURAS
'API CUMPLO
!global $COMPONENTE_API_CUMPLO = "Componente API Cumplo"
!global $COMPONENTE_API_CUMPLO_DESCRIP =  "Servicios Expuestos como API REST que hablan en idioma Cumplo"
!global $COMPONENTE_API_CUMPLO_TEC =   "Django RestFramework View"

'Autenticacion
!global $COMPONENTE_AUTENTICACION = "Componente Autenticación"
!global $COMPONENTE_AUTENTICACION_DESCRIP =  "Autentica las solucitudes de usuarios"
!global $COMPONENTE_AUTENTICACION_TEC =   "Python abstract class"

'Autentorizacion
!global $COMPONENTE_AUTORIZACION = "Componente Autorización"
!global $COMPONENTE_AUTORIZACION_DESCRIP =  "Valida permisos de usuarios"
!global $COMPONENTE_AUTORIZACION_TEC =   "Python abstract class"



'COMPONENTE FACTURA
!global $COMPONENTE_FACTURA = "Clase Factura"
!global $COMPONENTE_FACTURA_DESCRIP =  "almacena facturas, sus cesiones, pagos, indica si es real y confirmada"
!global $COMPONENTE_FACTURA_TEC =   "Django ORM"


'COMPONENTE Extraccion
!global $COMPONENTE_EXTRACCION = "Componente Extracción"
!global $COMPONENTE_EXTRACCION_DESCRIP =  "Extrae facturas desde sistemas externos y los almacena"
!global $COMPONENTE_EXTRACCION_TEC =   "Python abstract class"



'COMPONENTE COBRANZA
!global $COMPONENTE_COBRANZA = "Componente Cobranza"
!global $COMPONENTE_COBRANZA_DESCRIP =  "Interfaz para gestionar cobranza de facturas"
!global $COMPONENTE_COBRANZA_TEC =   "Python abstract class"


'COMPONENTE CESION
!global $COMPONENTE_CESION = "Componente Cesión"
!global $COMPONENTE_CESION_DESCRIP =  "cede facturas y registra cesión"
!global $COMPONENTE_CESION_TEC =   "Python abstract class"


'COMPONENTE NOTIFICACION
!global $COMPONENTE_NOTIFICACION = "Gestionador de notificaciones"
!global $COMPONENTE_NOTIFICACION_DESCRIP =  "Notifica de creación y actualizacion en la información de facturas"
!global $COMPONENTE_NOTIFICACION_TEC =   "Dependencia SNS, Botocode, de AWS"


'COMPONENTE LOGS
!global $COMPONENTE_LOGS = "Gestionador de logs de sistema"
!global $COMPONENTE_LOGS_DESCRIP =  "registra las acciones más importantes del módulo"
!global $COMPONENTE_LOGS_TEC =   "Dependencia WatchTower, Botocode, de AWS"

'COMPONENTE ERROR
!global $COMPONENTE_ERROR_SISTEMA = "Gestionador de errores de sistema"
!global $COMPONENTE_ERROR_SISTEMA_DESCRIP =  "notifica de errores de sistema"
!global $COMPONENTE_ERROR_SISTEMA_TEC =   "Dependencia Sentry"