!global $MODELO_ACTOR= "Participante"
!global $MODELO_MOVIMIENTO= "Movimiento Virtual"
!global $MODELO_PAGO= "Pago"
!global $MODELO_ACCESO= "Usuario"
!global $MODELO_TRANSACCION= "Transacción bancaria"

!global $MODELO_RESPALDO= "Factura"
!global $MODELO_CUENTA_VIRTUAL= "Cuenta Virtual"
!global $MODELO_AUTORIZACION="Permisos"
!global $MODELO_OPERACION="Operación"
!global $MODELO_INVERSION="Inversión"
!global $MODELO_NOMINA="Nómina"
!global $MODELO_DEPOSITO="Depósito"
!global $MODELO_ACCION = "Acción"