'CUENTAS REALES
!global $TITULO_CUENTAS_REALES = "Módulos Cuentas Reales"
!global $DESCRIPCION_CUENTAS_REALES = "El vigía de pagos y generador de nóminas. Mantiene el registro de cuentas reales, movimientos y saldos, como vienen desde el mundo exterior y los transforma en transacciones de ingreso y egreso."


'AUTENTICACION
!global $TITULO_AUTENTICACION = "Módulo Autenticación"
!global $DESCRIPCION_AUTENTICACION =  "Expone servicios para el consumo de sistemas externos a Cumplo y Verifica acceso según credenciales ingresadas, registra usuarios, cambia y resetea contraseñas."


'REGISTRO DE ACTORES
!global $TITULO_REGISTRO_ACTORES = "Módulo Registro de Participantes"
!global $DESCRIPCION_REGISTRO_ACTORES =  "El contenedor de los Participantes(Empresa/Persona) y su perfil detallado."

'CUENTAS VIRTUALES
!global $TITULO_CUENTAS_VIRTUALES= "Módulo Cuentas Virtuales"
!global $DESCRIPCION_CUENTAS_VIRTUALES =  "Gestión de cuentas virtuales, movimientos y saldos."


'CICLO VIDA OPERACION
!global $TITULO_CICLO_VIDA_OPERACION = "Ciclo de vida Operación"
!global $DESCRIPCION_CICLO_VIDA_OPERACION =   "Gestión de la operación y los procesos que giran en torno a la misma."

'RESPALDOS
!global $TITULO_RESPALDOS= "Módulo Respaldos y Facturas"
!global $DESCRIPCION_RESPALDOS =   "El supervisor de información de respaldos."

'AUTORIZACION
!global $TITULO_AUTORIZACION= "Módulo Autorizacion"
!global $DESCRIPCION_AUTORIZACION =   "indica quién puede y no puede realizar  acciones en los sistemas de cumplo."

!global $TITULO_CLIENTE_KOYWE = "Página de cliente"
!global $DESCRIPCION_CLIENTE_KOYWE =  "Llama a los servicios de Koywe mediante uso del Widget o la API"

!global $TITULO_WIDGET = "Widget de Koywe"
!global $DESCRIPCION_WIDGET =  "Servicios para realizar operaciones de on y off ramp (compra y venta)"

!global $TITULO_CORREOS = "Sistema de correos"
!global $DESCRIPCION_CORREOS =  "Envía correos a los usuarios (KYC) y a los clientes (Webhook)"

!global $TITULO_DB = "DataBase de Koywe"
!global $DESCRIPCION_DB =  "Almacena los datos de los clientes que se unan a Koywe, para poder reconocerlos."
