@startuml koyweService_pagos
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../C4_Context.puml
!include modulos.puml
!include modelos.puml
!include sistemas_externos.puml
!include relaciones.puml
!include usuarios.puml
!include perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Koywe in a nutshell

Person(user,$TITULO_SOLICITANTE_KOYWE, $DESCRIPCION_SOLICITANTE_KOYWE )

Enterprise_Boundary(c0, $PERIMETRO_KOYWE ) {
    System(modulo_on_off, $TITULO_KOYWE, $DESCRIPCION_KOYWE)
}
Enterprise_Boundary(cliente, $PERIMETRO_CLIENTE ) {
    System_Ext(cliente_koywe, $TITULO_CLIENTE_KOYWE ,$DESCRIPCION_CLIENTE_KOYWE )
}
System_Boundary(on_off, "Generación y recepción de pagos"){
    System_Ext(fireblock, "Fireblocks", "Plataforma para administrar y crear operaciones de compra y venta de crypto.")
    System_Ext(khipu, "Khipu", "Plataforma que facilita las transferencias bancarias (CHL/ARG).")
    'System_Ext(kushky, $S_EXT_TITULO_KUSHKY, $S_EXT_DESCRIPCION_KUSHKY)
    System_Ext(minka, "Minka", "Red de pagos, actualmente usada para las transacciones de Colombia.")
    System_Ext(fintoc, "Fintoc", "Plataforma para recibir transferencias bancarias en Chile")
    'System_Ext(rates, $S_EXT_TITULO_RATES, $S_EXT_DESCRIPCION_RATES)
    'System_Ext(shinkansen, $S_EXT_TITULO_SHINKANSEN, $S_EXT_DESCRIPCION_SHINKANSEN)
    System_Ext(transbank, "Transbank", "Servicio que ofrece medio de pago en Chile.")
    'System_Ext(vitawallet, $S_EXT_TITULO_VITAWALLET, $S_EXT_DESCRIPCION_VITAWALLET)
    System_Ext(stp, "STP", "Plataforma que provee medio medio de pagos en México para onramp y offramp.")
    System_Ext(palomma, "Palomma", "Medio de pago para COL, soporta banColombia y Neki (wallet).")
    System_Ext(moneda, "Moneda", "Servicio de corredora de bolsa de fondo mutuo.")
    System_Ext(transfiya, "TransfiYa", "Medio de pago para COL.")
    System_Ext(wiremx, "WIREMX", "Medio de pago para MEX. Se conecta con STP.")
}


'RELACIONES DE SISTEMA
'Relaciones sistema/módulos

'Relaciones usuarios/sitios
Rel(modulo_on_off,user, "Envía correos para KYC/estado de transacción")
Rel(user, cliente_koywe, "Solicita contenido")
Rel(cliente_koywe, modulo_on_off, "Llama los servicios")

Rel(modulo_on_off, fireblock,"Gestión de Wallets y transacciones crypto")
Rel(modulo_on_off, khipu, "Genera transferencias bancarias en CHL y ARG")
'Rel(modulo_on_off, kushky,"")
Rel(modulo_on_off, minka, "Generar y recibir transacciones bancarias en COL")
Rel(modulo_on_off, fintoc,"Recibir pagos de los usuarios, para onramp.")
'Rel(modulo_on_off, rates,$RELACION_CLIENTE_KOYWE)
'Rel(modulo_on_off, shinkansen,$RELACION_CLIENTE_KOYWE)
Rel(modulo_on_off, transbank,"Recibir pagos de los usuarios, para onramp.")
Rel(modulo_on_off, stp, "Genera credenciales asignadas a los usuarios mexicanos. Administra operaciones de compra onramp y offramp.")
Rel(modulo_on_off, palomma, "Recibir pagos de los usuarios, para onramp.")
Rel(modulo_on_off, moneda, "Recibir pagos de los usuarios, para onramp.")
Rel(modulo_on_off, transfiya, "Recibir pagos de los usuarios, para onramp.")
Rel(stp, wiremx, "")






@enduml
