@startuml koywe_c2
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include ../C4_Context.puml
!include modulos.puml
!include modelos.puml
!include sistemas_externos.puml
!include relaciones.puml
!include usuarios.puml
!include perimetros.puml
!include ../C4_Container.puml

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml

!include <office/Servers/database_server>
!include <office/Servers/file_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/firewall>
!include <office/Concepts/application_generic>
!include <office/Services/email_service>
!include <office/Services/online_hosted_services>

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Koywe in a nutshell

'AddElementTag("v1.0", $borderColor="#d73027")
'AddElementTag("v1.1", $fontColor="#d73027")
'AddElementTag("backup", $fontColor="orange")

AddElementTag("micro service", $shape=RoundedBoxShape(), $bgColor="Yellow", $sprite="service_application", $fontColor="white")
AddElementTag("storage", $shape=RoundedBoxShape(), $sprite="database_server", $fontColor="white")
AddRelTag("linea", $textColor="Gray", $lineColor="Gray", $lineStyle = DashedLine())
AddContainerTag("webApp", $sprite="application_generic", $legendText="web app container")
AddContainerTag("mail", $sprite="email_service", $legendText="web app container")
AddContainerTag("widget", $sprite="online_hosted_services", $legendText="web app container")

System_Boundary(c0, $PERIMETRO_KOYWE ) {
    Container(correo, "Sistema de Correos", "Envía emails a los usuarios para hacer KYC y Order Tracking y a clientes para hacer Webhook.", $tags = "mail")
    ContainerDb(db, "Base de Datos de Koywe", "Almacena los datos de los clientes, como su clientId, Secret, y email. Almacena OrderId. MongoDB", $tags = "storage")
    Container(widget, "Widget de Koywe", "Permite realizar operaciones de onramp y offramp", $tags = "widget")
    Container(api, "API de Koywe", "Permite realizar operaciones de onramp y offramp", $tags = "micro service")
    Container(page, "Página Web de Koywe", "Plataforma introductoria a los clientes nuevos de Koywe", $tags = "webApp")
    Container(ticker, "ticker", "Generador de precios para Koywe")
    Container(Scrapping, "Scrapping Santander CHL", "Consulta los depósitos al banco Santander en Chile y los registra en Koywe")
    Container(iframe, "iframe", "Permite realizar operaciones de onramp y offramp", $tags = "webApp")
    
}

'System_Boundary(externo, "Sistemas Externos"){
'    System_Ext(ramp, "Generación y recepción de pagos")
'    System_Ext(kyc, "Registro de usuario")
'    System_Ext(facturas, "Facturación")
'    System_Ext(deploy, "Despliege de aplicaciones Koywe")
'    System_Ext(consultoras, "Consultoras de precios de token-fiat")
'    System_Ext(bancos, "Bancos")
'}
System_Boundary(ramp, "Generación y recepción de pagos")
System_Boundary(kyc, "Registro de usuario")
System_Boundary(facturas, "Facturación")
System_Boundary(deploy, "Despliege de aplicaciones Koywe")
System_Boundary(consultoras, "Consultoras de precios de token-fiat")
System_Boundary(bancos, "Bancos")


Person(user,$TITULO_SOLICITANTE_KOYWE, $DESCRIPCION_SOLICITANTE_KOYWE )

Enterprise_Boundary(cliente, $PERIMETRO_CLIENTE ) {
    System_Ext(cliente_koywe, $TITULO_CLIENTE_KOYWE ,$DESCRIPCION_CLIENTE_KOYWE )
}

Rel(user, cliente_koywe,"Solicita contenido", $tags="linea")
Rel_U(correo,user, "Envía correos para KYC/estado de transacción", $tags="linea")
Rel(page,widget, "Consume", $tags="linea")

Rel(cliente_koywe, widget, "Consume", $tags="linea")
Rel(cliente_koywe, api,"usa los servicios", "JSON/HTTPS, GraphQL", $tags="linea")
'Rel(correo, cliente_koywe,"Webhooks")

Rel(widget, api,"Hace llamados a", "GraphQL", $tags="linea")

Rel(api, db,"Lee y escribe a ", "MongoDB wire protocol", $tags="linea")
Rel(api, correo,"Hace llamados a", "JSON/HTTPS", $tags="linea")

Rel(Scrapping, api,"Lee y escribe a ", "JSON/HTTPS", $tags="linea")
Rel(Scrapping, db,"Hace llamados a", "MongoDB wire protocol", $tags="linea")

Rel(ticker, db,"Hace llamados a", "MongoDB wire protocol", $tags="linea")

Rel(iframe, widget,"Consume", $tags="linea")
Rel(cliente_koywe, iframe,"usa los servicios", $tags="linea")


Rel(api, ramp,"")
Rel(api, kyc,"")
Rel(api, facturas,"")
Rel(api, deploy,"")
Rel(api, consultoras,"")
Rel(api, bancos,"")
Rel(ticker, consultoras, "")
Rel(Scrapping, bancos,"")

Lay_U(user, cliente)










@enduml