@startuml koyweService
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../C4_Context.puml
!include modulos.puml
!include modelos.puml
!include sistemas_externos.puml
!include relaciones.puml
!include usuarios.puml
!include perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Koywe in a nutshell

Person(user,$TITULO_SOLICITANTE_KOYWE, $DESCRIPCION_SOLICITANTE_KOYWE )

Enterprise_Boundary(c0, $PERIMETRO_KOYWE ) {
    System(modulo_on_off, "Sistema Koywe", $DESCRIPCION_WIDGET)
}
Enterprise_Boundary(cliente, $PERIMETRO_CLIENTE ) {
    System_Ext(cliente_koywe, $TITULO_CLIENTE_KOYWE ,$DESCRIPCION_CLIENTE_KOYWE )
}
System_Boundary(sistemas_externos, $PERIMETRO_SISTEMAS_EXTERNOS){
    System_Boundary(on_off, "Generación y recepción de pagos"){
        System_Ext(fireblock, $S_EXT_TITULO_FIREBLOCK, $S_EXT_DESCRIPCION_FIREBLOCK)
        System_Ext(khipu, $S_EXT_TITULO_KHIPU, $S_EXT_DESCRIPCION_KHIPU)
        'System_Ext(kushky, $S_EXT_TITULO_KUSHKY, $S_EXT_DESCRIPCION_KUSHKY)
        System_Ext(minka, $S_EXT_TITULO_MINKA, $S_EXT_DESCRIPCION_MINKA)
        System_Ext(fintoc, $S_EXT_TITULO_FINTOC, $S_EXT_DESCRIPCION_FINTOC)
        'System_Ext(rates, $S_EXT_TITULO_RATES, $S_EXT_DESCRIPCION_RATES)
        'System_Ext(shinkansen, $S_EXT_TITULO_SHINKANSEN, $S_EXT_DESCRIPCION_SHINKANSEN)
        System_Ext(transbank, $S_EXT_TITULO_TRANSBANK, $S_EXT_DESCRIPCION_TRANSBANK)
        'System_Ext(vitawallet, $S_EXT_TITULO_VITAWALLET, $S_EXT_DESCRIPCION_VITAWALLET)
        System_Ext(stp, "STP", "Plataforma que provee medio medio de pagos en México para onramp y offramp.")
        System_Ext(paloma, "Paloma", "Medio de pago para COL")
    }
    System_Boundary(kyc, "KYC"){
        System_Ext(metamap, $S_EXT_TITULO_METAMAP, $S_EXT_DESCRIPCION_METAMAP)
    }
    System_Boundary(facturas, "Facturación"){
        System_Ext(invopop, "Invopop", "Servicio para automatizar facturas electrónicas.")
        System_Ext(google, "Google Maps", "Servicio de mapas para direcciones.")
    }
    System_Boundary(sistemas_externos_dev, "Despliege de aplicaciones Koywe"){
        System_Ext(github, "Github", "Plataforma de trabajo para almacenar, modificar y versionar código compartido remotamente.")
        System_Ext(aws, "AWS", "Plataforma que despliega la infraestructura del backend.")
        System_Ext(vercel, "Vercel", "plataforma que despliega la infraestrucutra del frontend.") 
    }
}

System_Boundary(bancos, "Bancos"){
    System_Ext(banco_pe1, "BBVA", "Cuenta de Koywe en Perú.")
    System_Ext(banco_pe2, "BCP", "Cuenta de Koywe en Perú.")
    System_Ext(banco_chl1, "Santander", "Cuenta de Koywe en Chile.")
    System_Ext(banco_col1, "Banco Colombia NN", "Cuenta de Koywe en Colombia.")
    System_Ext(banco_mex1, "Banco Mexicano NN", "Cuenta de Koywe en México.")
}
System_Boundary(exchange, "Consultoras de precios de token-fiat"){
    System_Ext(coingecko, "CoinGecko", "Plataforma para consultar precios crypto-fiat.")
    System_Ext(bitso, "Bitso", "Plataforma de servicios de crypto en latinoamérica. Permite comprar, vender y guardas crypto.")
    System_Ext(buda, "Buda", "Permite consultar precios de variadas criptomonedas.")
    System_Ext(mkt, "CryptoMKT", "Plataforma para consultar precios crypto-fiat.")
}

'RELACIONES DE SISTEMA
'Relaciones sistema/módulos

'Relaciones usuarios/sitios
Rel(modulo_on_off,user, $RELACION_MAIL_USUARIO)
Rel(user, cliente_koywe,$RELACION_USUARIO_CLIENTE)
Rel(cliente_koywe, modulo_on_off,$RELACION_CLIENTE_KOYWE)

Rel(modulo_on_off, fireblock,$RELACION_FIREBLOCK)
Rel(modulo_on_off, khipu, $RELACION_KHIPU)
'Rel(modulo_on_off, kushky,"")
Rel(modulo_on_off, metamap, $RELACION_METAMAP)
Rel(modulo_on_off, minka, $RELACION_MINKA)
Rel(modulo_on_off, fintoc,$RELACION_FINTOC)
'Rel(modulo_on_off, rates,$RELACION_CLIENTE_KOYWE)
'Rel(modulo_on_off, shinkansen,$RELACION_CLIENTE_KOYWE)
Rel(modulo_on_off, transbank,$RELACION_TRANSBANK)

Rel(modulo_on_off, invopop, "Generar y administrar boletas y facturas")
Rel(modulo_on_off, google, "Validar dirección de usuario")

Rel(modulo_on_off, github, "versionamiento de código")
Rel(modulo_on_off, vercel, "despliega la infraestructura del frontend.")
Rel(modulo_on_off, aws, "despliega la infraestructura del backend.")
Rel(modulo_on_off, stp, "Genera credenciales asignadas a los usuarios mexicanos. Administra operaciones de compra onramp y offramp.")
Rel(modulo_on_off, paloma, "Generar y recibir transferencias bancarias")

Rel(modulo_on_off, banco_chl1,"Obtiene depósitos CHL en CLP")
Rel(modulo_on_off, banco_col1,"Obtiene depósitos COL en COP")
Rel(modulo_on_off, banco_mex1,"Obtiene depósitos MEX en MXN")
Rel(modulo_on_off, banco_pe1,"Obtiene depósitos PE en PEN")
Rel(modulo_on_off, banco_pe2,"Obtiene depósitos PE en PEN")

Rel(modulo_on_off, coingecko,"Consulta precios de [BNB-MXN, USDC-MXN, MATIC-MXN, BNB-CLP, MATIC-CLP, DAI-CLP]")
Rel(modulo_on_off, bitso,"Consulta precios de [DAI-MXN, BTC-MXN, ETH-MXN, USDT-COP, USDT-MXN]")
Rel(modulo_on_off, buda,"Consulta precios de [USDC-PEN, BTC-PEN, BTC-CLP, ETH-CLP, ETH-COP, USDC-CLP, BTC-COP, USDC-COP, ETH-PEN]")
Rel(modulo_on_off, mkt,"Consulta precios de [USDT-CLP, USDT-PEN]")
'Rel(modulo_on_off, vitawallet,$RELACION_VITAWALLET)

Lay_D(cliente, sistemas_externos_dev)

Lay_D(banco_chl1, banco_col1)
Lay_D(banco_col1, banco_mex1)
Lay_D(banco_mex1, banco_pe1)
Lay_D(banco_pe1, banco_pe2)

Lay_D(coingecko, bitso)
Lay_D(bitso, buda)

Lay_D(khipu, metamap)
Lay_D(minka, fintoc)
Lay_D(transbank, invopop)
Lay_D(stp, fireblock)




@enduml
