@startuml koyweService
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../C4_Context.puml
!include modulos.puml
!include modelos.puml
!include sistemas_externos.puml
!include relaciones.puml
!include usuarios.puml
!include perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Koywe in a nutshell

Person_Ext(user,$TITULO_SOLICITANTE_KOYWE, $DESCRIPCION_SOLICITANTE_KOYWE )

Enterprise_Boundary(c0, $PERIMETRO_KOYWE ) {
    System(modulo_on_off, "Sistema Koywe", $DESCRIPCION_WIDGET)
}
Enterprise_Boundary(cliente, $PERIMETRO_CLIENTE ) {
    System_Ext(cliente_koywe, $TITULO_CLIENTE_KOYWE ,$DESCRIPCION_CLIENTE_KOYWE )
}
System_Boundary(sistemas_externos, $PERIMETRO_SISTEMAS_EXTERNOS){
    System_Ext(fireblock, $S_EXT_TITULO_FIREBLOCK, $S_EXT_DESCRIPCION_FIREBLOCK)
    System_Ext(khipu, $S_EXT_TITULO_KHIPU, $S_EXT_DESCRIPCION_KHIPU)
    'System_Ext(kushky, $S_EXT_TITULO_KUSHKY, $S_EXT_DESCRIPCION_KUSHKY)
    System_Ext(metamap, $S_EXT_TITULO_METAMAP, $S_EXT_DESCRIPCION_METAMAP)
    System_Ext(minka, $S_EXT_TITULO_MINKA, $S_EXT_DESCRIPCION_MINKA)
    System_Ext(fintoc, $S_EXT_TITULO_FINTOC, $S_EXT_DESCRIPCION_FINTOC)
    'System_Ext(rates, $S_EXT_TITULO_RATES, $S_EXT_DESCRIPCION_RATES)
    'System_Ext(shinkansen, $S_EXT_TITULO_SHINKANSEN, $S_EXT_DESCRIPCION_SHINKANSEN)
    System_Ext(transbank, $S_EXT_TITULO_TRANSBANK, $S_EXT_DESCRIPCION_TRANSBANK)
    System_Ext(vitawallet, $S_EXT_TITULO_VITAWALLET, $S_EXT_DESCRIPCION_VITAWALLET)
}



'RELACIONES DE SISTEMA
'Relaciones sistema/módulos

'Relaciones usuarios/sitios
Rel(modulo_on_off,user, $RELACION_MAIL_USUARIO)
Rel(user, cliente_koywe,$RELACION_USUARIO_CLIENTE)
Rel(cliente_koywe, modulo_on_off,$RELACION_CLIENTE_KOYWE)

Rel(modulo_on_off, fireblock,$RELACION_FIREBLOCK)
Rel(modulo_on_off, khipu, $RELACION_KHIPU)
'Rel(modulo_on_off, kushky,"")
Rel(modulo_on_off, metamap, $RELACION_METAMAP)
Rel(modulo_on_off, minka, $RELACION_MINKA)
Rel(modulo_on_off, fintoc,$RELACION_FINTOC)
'Rel(modulo_on_off, rates,$RELACION_CLIENTE_KOYWE)
'Rel(modulo_on_off, shinkansen,$RELACION_CLIENTE_KOYWE)
Rel(modulo_on_off, transbank,$RELACION_TRANSBANK)
Rel(modulo_on_off, vitawallet,$RELACION_VITAWALLET)



'declaraciones para distribución espacial
Lay_D(user, c0)

'Lay_D(cliente, modulo_on_off)
Lay_R(user, cliente)



@enduml
