@startuml koyweService_C3
'!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
!include ../C4_Context.puml
!include modulos.puml
!include modelos.puml
!include sistemas_externos.puml
!include relaciones.puml
!include usuarios.puml
!include perimetros.puml
!include ../C4_Container.puml
!include ../C4_Component.puml

!define osaPuml https://raw.githubusercontent.com/Crashedmind/PlantUML-opensecurityarchitecture2-icons/master
!include osaPuml/Common.puml
!include osaPuml/User/all.puml

!include <office/Servers/database_server>
!include <office/Servers/file_server>
!include <office/Servers/application_server>
!include <office/Concepts/service_application>
!include <office/Concepts/firewall>
!include <office/Concepts/application_generic>
!include <office/Services/email_service>
!include <office/Services/online_hosted_services>

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Koywe in a nutshell

'AddElementTag("v1.0", $borderColor="#d73027")
'AddElementTag("v1.1", $fontColor="#d73027")
'AddElementTag("backup", $fontColor="orange")

AddElementTag("storage", $shape=RoundedBoxShape() , $sprite="database_server", $fontColor="white")
AddRelTag("linea", $textColor="Gray", $lineColor="Gray", $lineStyle = DashedLine())
AddContainerTag("mail", $sprite="email_service", $legendText="web app container")
AddContainerTag("widget", $sprite="online_hosted_services", $legendText="web app container")


Container(widget, "Widget de Koywe", "Permite realizar operaciones de onramp y offramp", $tags = "widget")
System_Ext(cliente_koywe, $TITULO_CLIENTE_KOYWE ,$DESCRIPCION_CLIENTE_KOYWE )

Container_Boundary(c0, "API de Koywe" ) {
    
    Component(balanceaccount, "Balance Account", "LLeva registro de los movimientos en la cuenta de un usuario, y sabe su saldo. Balances por cuenta, moneda y pais.")
    Component(exchange, "Exchange Rate", "Consulta precios de crypto a USD.")
    Component(functions, "Functions", "Expone servicios Koywe en aws Lambda como REST.")
    Component(resolvers, "Resolvers", "Expone servicios de Koywe en aws lambda  como GraphQL")

    Component(servicios, "Servicios", "")

    Component(order, "Servicios Order", "Servicios para crear y consultar órdenes.")
    Component(currency, "Servicios Currency", "Servicios para consultar pares.")
    Component(tokens, "Servicios Tokens", "Servicios para consultar pares.")
    Component(paymentprovider, "Servicios métodos de pago", "Servicios para consultar medio de pago disponibles.")
    Component(auth, "Servicios de autenticación", "Servicios para autenticar al usuario con una sesión.")
    Component(quote, "Servicios de quotes", "Servicios para crear y consultar quotes de operaciones.")
    Component(bank, "Servicios de cuentas bancarias", "Servicios para crear y consultar cuentas bancarias registradas.")
    Component(document, "Servicios de data del usuario", "Servicios para guardar información del usuario.")
    Component(contenedor, "Contenedor de facturación", "Genera las facturas a nuestros usuarios a partir de las órdenes creadas.")
    
}


Container(correo, "Sistema de Correos", "Envía emails a los usuarios para hacer KYC y Order Tracking y a clientes para hacer Webhook.", $tags = "mail")
ContainerDb(db, "Base de Datos de Koywe", "Almacena los datos de los clientes, como su clientId, Secret, y email. Almacena OrderId. MongoDB", $tags = "storage")

Rel(resolvers, servicios, "", $tags="linea")
Rel(functions, servicios, "", $tags="linea")

Rel(servicios, currency, "", $tags="linea")
Rel(servicios, tokens, "", $tags="linea")
Rel(servicios, paymentprovider, "", $tags="linea")
Rel(servicios, auth, "", $tags="linea")
Rel(servicios, quote, "", $tags="linea")
Rel(servicios, bank, "", $tags="linea")
Rel(servicios, document, "", $tags="linea")
Rel(servicios, order, "", $tags="linea")

Rel(order, correo,"Hace llamados a", "JSON/HTTPS", $tags="linea")
Rel(auth, correo,"Hace llamados a", "JSON/HTTPS", $tags="linea")

Rel(order, db,"Lee y escribe a ", "MongoDB wire protocol", $tags="linea")
Rel(quote, db,"Lee y escribe a ", "MongoDB wire protocol", $tags="linea")
Rel(bank, db,"Lee y escribe a ", "MongoDB wire protocol", $tags="linea")
Rel(auth, db,"Lee y escribe a ", "MongoDB wire protocol", $tags="linea")
Rel(document, db,"escribe a ", "MongoDB wire protocol", $tags="linea")

Rel(currency, db,"Lee a ", "MongoDB wire protocol", $tags="linea")
Rel(tokens, db,"Lee a ", "MongoDB wire protocol", $tags="linea")
Rel(paymentprovider, db,"Lee a ", "MongoDB wire protocol", $tags="linea")


Rel(widget, functions,"Consume", $tags="linea")
Rel(cliente_koywe, resolvers,"Consume", $tags="linea")
Rel(cliente_koywe, functions,"Consume", $tags="linea")

Rel(balanceaccount, db,"Lee y escribe a ", "MongoDB wire protocol", $tags="linea")
Rel(exchange, db,"escribe a ", "MongoDB wire protocol", $tags="linea")

Rel(contenedor, db,"lee a ", "MongoDB wire protocol", $tags="linea")

Rel(exchange, quote,"", $tags="linea")
Rel(balanceaccount, order,"", $tags="linea")

Lay_D(widget, c0)
Lay_D(cliente_koywe, c0)
Lay_R(cliente_koywe, widget)

Lay_D(functions, order)
Lay_D(resolvers, order)

Lay_D(functions, balanceaccount)
Lay_D(resolvers, balanceaccount)

Lay_D(functions, exchange)
Lay_D(resolvers, exchange)

Lay_D(functions, currency)
Lay_D(resolvers, currency)

Lay_D(functions, tokens)
Lay_D(resolvers, tokens)

Lay_D(functions, paymentprovider)
Lay_D(resolvers, paymentprovider)

Lay_D(functions, auth)
Lay_D(resolvers, auth)

Lay_D(functions, quote)
Lay_D(resolvers, quote)

Lay_D(functions, bank)
Lay_D(resolvers, bank)

Lay_D(functions, document)
Lay_D(resolvers, document)


@enduml