@startuml koyweService_ext
' !include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml
!include ../C4_Context.puml
!include modulos.puml
!include modelos.puml
!include sistemas_externos.puml
!include relaciones.puml
!include usuarios.puml
!include perimetros.puml

'LAYOUT_TOP_DOWN()
'LAYOUT_AS_SKETCH()
LAYOUT_WITH_LEGEND()

title Koywe in a nutshell

Person(user,$TITULO_SOLICITANTE_KOYWE, $DESCRIPCION_SOLICITANTE_KOYWE )

Enterprise_Boundary(c0, $PERIMETRO_KOYWE ) {
    System(modulo_on_off, $TITULO_KOYWE, $DESCRIPCION_KOYWE)
}
Enterprise_Boundary(cliente, $PERIMETRO_CLIENTE ) {
    System_Ext(cliente_koywe, $TITULO_CLIENTE_KOYWE ,$DESCRIPCION_CLIENTE_KOYWE )
}

System_Boundary(kyc, "Registro de usuario"){
    System_Ext(metamap, "Metamap", "Servicio que entrega las herramientas para hacer KYC (Know Your Customer).")
    System_Ext(google, "Google Maps", "Servicio de mapas para direcciones.")
}
System_Boundary(facturas, "Facturación"){
    System_Ext(invopop, "Invopop", "Servicio para automatizar facturas electrónicas.")
    System_Ext(bsale, "bsale", "Emisión de documentos tributarios electrónicos para CHL.")
}
System_Boundary(sistemas_externos_dev, "Despliege de aplicaciones Koywe"){
    System_Ext(github, "Github", "Plataforma de trabajo para almacenar, modificar y versionar código compartido remotamente.")
    System_Ext(aws, "AWS", "Plataforma que despliega la infraestructura del backend.")
    System_Ext(vercel, "Vercel", "plataforma que despliega la infraestrucutra del frontend.") 
    System_Ext(azure, "Azure", "plataforma que despliega la infraestrucutra del backend (Cosigner Fireblocks).") 
}


'RELACIONES DE SISTEMA
'Relaciones sistema/módulos

'Relaciones usuarios/sitios
Rel(modulo_on_off,user, "Envía correos para KYC/estado de transacción")
Rel(user, cliente_koywe, "Solicita contenido")
Rel(cliente_koywe, modulo_on_off, "Llama los servicios")

Rel(modulo_on_off, invopop, "Generar y administrar facturas")
Rel(modulo_on_off, bsale, "Generar y administrar facturas")
Rel(modulo_on_off, google, "Validar dirección de usuario")

Rel(modulo_on_off, github, "versionamiento de código")
Rel(modulo_on_off, vercel, "despliega la infraestructura del frontend.")
Rel(modulo_on_off, aws, "despliega la infraestructura del backend.")

Rel(modulo_on_off, metamap, "Verificación de cuentas de usuario (KYC)")






@enduml
